### PR TITLE
Partial Python 2.7 support

### PR DESCRIPTION
**Pull request by jayvdb**
Add backports, and implement isprintable

Fixes https://github.com/Ousret/charset_normalizer/issues/1

### CODE REVIEW

**Comment by jayvdb** [comment]
There are quite a few more py2 str/unicode problems, but this at least gets most of the tests working

**Comment by jayvdb** [comment]
I've limited the scope to not include the str/bytes/unicode problem.
My hacks are in https://github.com/jayvdb/charset_normalizer/tree/py2-decoding and tests are at https://travis-ci.org/jayvdb/charset_normalizer/jobs/577912355 - a lot more needs to be done to get that working properly.

**Comment by jayvdb** [comment]
ping @Ousret . If you are going to keep Python 2 on the TODO list, I'm happy to keep chipping away at the problem.

**Comment by Ousret** [comment]
- Python 2.7 EOL Scheduled January 1st, 2020.
  - 1 Million package dl python 2 as of today but decreasing 

So I am going to close that. #1

**Comment by jayvdb** [comment]
Fair enough ;-)

We can always revisit this if someone needs py2.

**Pull request closed without merging**
