### PR TITLE
:bug: Fix very rare case of ?bad? bytes payload that cause decode/encode errors

### PR DESCRIPTION
**Pull request by Ousret**
Linked to https://github.com/psf/requests/pull/5797#issuecomment-840362338

### CODE REVIEW

**Comment by potiuk** [comment]
Cool

**Comment by Ousret** [comment]
So I can herbally confirm that this patch fixes the issue. The websites that raise that are behind the Cloudflare app-firewall I noticed.

**Comment by Ousret** [comment]
I am merging this now as it does not interfere with everything else. This 'bug' is a very edge case and seems related to errors in TX.

**Comment by potiuk** [comment]
Cool. I can re-run the test tomorrow for all 33.000 sites - it was pretty repeatable with 16-18 cases per run.

**Pull request merged**
