### PR TITLE
v2.0.1

### PR DESCRIPTION
**Pull request by Ousret**
*Changes:*

  - **Bugfix:** :bug: Make it work where there isn't a filesystem available #54 #55 
  - **Improvement:** :sparkles: You may now use aliases in `cp_isolation` and `cp_exclusion` arguments #47 
  - **Bugfix:** :bug: Using explain=False permanently disable the verbose output in the current runtime #47 
  - **Bugfix:** :bug: One log entry (language target preemptive) was not show in logs when using `explain=True` #47 
  - **Bugfix:** :bug: Fix undesired exception (ValueError) on getitem of instance CharsetMatches #52 
  - **Improvement:** :wrench: Public function `normalize` default args values were not aligned with `from_bytes`  #53

### CODE REVIEW

**Comment by sethmlarson** [comment]
Have you done integration testing with Requests for this release?

**Comment by Ousret** [comment]
Yes. Doing these as we speak. I need more time to finish these, but will soon. I will try to add an automated action afterward.

**Comment by Ousret** [comment]
Do you have any more concerns regarding the core architecture?

**Comment by sethmlarson** [comment]
@Ousret I didn't find any other problems no. I was curious about https://github.com/Ousret/charset_normalizer/blob/master/charset_normalizer/hook.py as it looks like it tries to use `unicodedata2` which is a backport for Python 2? Maybe that file isn't needed anymore?

> Yes. Doing these as we speak. I need more time to finish these, but will soon. I will try to add an automated action afterward.

Feel free to copy urllib3's integration testing format if you need inspiration.

**Comment by Ousret** [comment]
Everything is OK! Will proceed then.

**Pull request merged**
